# Generated by Django 2.2.10 on 2023-03-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Longitude', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Group')),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hospital')),
            ],
        ),
    ]
